"""Per-species components attached to a dino: stats, inventory, AI and harvest tables."""

class StatusComponents:
    acrocanthosaurus: str = "/Game/ASA/Dinos/Acrocanthosaurus/DinoCharacterStatusComponent_BP_Acrocanthosaurus.DinoCharacterStatusComponent_BP_Acrocanthosaurus_C"
    archelon_asa: str = "/Game/ASA/Dinos/Archelon/Dinos/DinoCharacterStatus_BP_Archelon_ASA.DinoCharacterStatus_BP_Archelon_ASA_C"
    bison: str = "/Game/ASA/Dinos/Bison/DinoCharacterStatusComponent_BP_Bison.DinoCharacterStatusComponent_BP_Bison_C"
    boaratos: str = "/Game/ASA/Dinos/Boaratos/DinoCharacterStatusComponent_BP_Boaratos.DinoCharacterStatusComponent_BP_Boaratos_C"
    cat: str = "/Game/ASA/Dinos/Cat/DinoCharacterStatusComponent_BP_Cat.DinoCharacterStatusComponent_BP_Cat_C"
    ceratosaurus_asa: str = "/Game/ASA/Dinos/Ceratosaurus/Dinos/DinoCharacterStatusComponent_BP_Ceratosaurus_ASA.DinoCharacterStatusComponent_BP_Ceratosaurus_ASA_C"
    concavenator: str = "/Game/ASA/Dinos/Concavenator/DinoCharacterStatusComponent_BP_Concavenator.DinoCharacterStatusComponent_BP_Concavenator_C"
    cryolophosaurus: str = "/Game/ASA/Dinos/Cryolophosaurus/DinoCharacterStatusComponent_BP_Cryolophosaurus.DinoCharacterStatusComponent_BP_Cryolophosaurus_C"
    dark_pegasus: str = "/Game/ASA/Dinos/DarkPegasus/DinoCharacterStatusComponent_BP_DarkPegasus.DinoCharacterStatusComponent_BP_DarkPegasus_C"
    deino_asa: str = "/Game/ASA/Dinos/Deinosuchus/DinoCharacterStatus_BP_Deino_ASA.DinoCharacterStatus_BP_Deino_ASA_C"
    deinotherium_asa: str = "/Game/ASA/Dinos/Deinotherium/Dinos/DinoCharacterStatusComponent_BP_Deinotherium_ASA.DinoCharacterStatusComponent_BP_Deinotherium_ASA_C"
    dreadnoughtus: str = "/Game/ASA/Dinos/Dreadnoughtus/DinoCharacterStatusComponent_BP_Dreadnoughtus.DinoCharacterStatusComponent_BP_Dreadnoughtus_C"
    fasola: str = "/Game/ASA/Dinos/Fasolasuchus/DinoCharacterStatusComponent_BP_Fasola.DinoCharacterStatusComponent_BP_Fasola_C"
    fire_lion: str = "/Game/ASA/Dinos/FireLion/DinoCharacterStatusComponent_BP_FireLion.DinoCharacterStatusComponent_BP_FireLion_C"
    gigantoraptor: str = "/Game/ASA/Dinos/Gigantoraptor/DinoCharacterStatusComponent_BP_Gigantoraptor.DinoCharacterStatusComponent_BP_Gigantoraptor_C"
    helicoprion: str = "/Game/ASA/Dinos/Helicoprion/DinoCharacterStatusComponent_BP_Helicoprion.DinoCharacterStatusComponent_BP_Helicoprion_C"
    jackalope: str = "/Game/ASA/Dinos/Jackalope/DinoCharacterStatusComponent_BP_Jackalope.DinoCharacterStatusComponent_BP_Jackalope_C"
    val_megaraptor: str = "/Game/ASA/Dinos/Megaraptor/DinoCharacterStatusComponent_BP_ValMegaraptor.DinoCharacterStatusComponent_BP_ValMegaraptor_C"
    shastasaurus: str = "/Game/ASA/Dinos/Shastasaurus/DinoCharacterStatusComponent_BP_Shastasaurus.DinoCharacterStatusComponent_BP_Shastasaurus_C"
    shoulder_dragon: str = "/Game/ASA/Dinos/ShoulderDragon/DinoCharacterStatusComponent_BP_ShoulderDragon.DinoCharacterStatusComponent_BP_ShoulderDragon_C"
    s_bear: str = "/Game/ASA/Dinos/SpiritBear/Gameplay/DinoCharacterStatusComponent_BP_SBear.DinoCharacterStatusComponent_BP_SBear_C"
    xiph_asa: str = "/Game/ASA/Dinos/Xiphactinus/Dinos/DinoCharacterStatus_BP_Xiph_ASA.DinoCharacterStatus_BP_Xiph_ASA_C"
    yi_ling: str = "/Game/ASA/Dinos/YiLing/DinoCharacterStatusComponent_BP_YiLing.DinoCharacterStatusComponent_BP_YiLing_C"
    basilisk: str = "/Game/Aberration/CoreBlueprints/DinoCharacterStatusComponent_BP_Basilisk.DinoCharacterStatusComponent_BP_Basilisk_C"
    basilisk_alpha: str = "/Game/Aberration/CoreBlueprints/DinoCharacterStatusComponent_BP_Basilisk_Alpha.DinoCharacterStatusComponent_BP_Basilisk_Alpha_C"
    cave_crab: str = "/Game/Aberration/CoreBlueprints/DinoCharacterStatusComponent_BP_CaveCrab.DinoCharacterStatusComponent_BP_CaveCrab_C"
    cave_crab_alpha: str = "/Game/Aberration/CoreBlueprints/DinoCharacterStatusComponent_BP_CaveCrab_Alpha.DinoCharacterStatusComponent_BP_CaveCrab_Alpha_C"
    chupa_cabra: str = "/Game/Aberration/CoreBlueprints/DinoCharacterStatusComponent_BP_ChupaCabra.DinoCharacterStatusComponent_BP_ChupaCabra_C"
    lantern_bird: str = "/Game/Aberration/CoreBlueprints/DinoCharacterStatusComponent_BP_LanternBird.DinoCharacterStatusComponent_BP_LanternBird_C"
    lantern_goat: str = "/Game/Aberration/CoreBlueprints/DinoCharacterStatusComponent_BP_LanternGoat.DinoCharacterStatusComponent_BP_LanternGoat_C"
    lantern_lizard: str = "/Game/Aberration/CoreBlueprints/DinoCharacterStatusComponent_BP_LanternLizard.DinoCharacterStatusComponent_BP_LanternLizard_C"
    lantern_pug: str = "/Game/Aberration/CoreBlueprints/DinoCharacterStatusComponent_BP_LanternPug.DinoCharacterStatusComponent_BP_LanternPug_C"
    mole_rat: str = "/Game/Aberration/CoreBlueprints/DinoCharacterStatusComponent_BP_MoleRat.DinoCharacterStatusComponent_BP_MoleRat_C"
    pteroteuthis: str = "/Game/Aberration/CoreBlueprints/DinoCharacterStatusComponent_BP_Pteroteuthis.DinoCharacterStatusComponent_BP_Pteroteuthis_C"
    xenomorph_chupa: str = "/Game/Aberration/CoreBlueprints/DinoCharacterStatusComponent_BP_Xenomorph_Chupa.DinoCharacterStatusComponent_BP_Xenomorph_Chupa_C"
    xenomorph_queen: str = "/Game/Aberration/CoreBlueprints/DinoCharacterStatusComponent_BP_Xenomorph_Queen.DinoCharacterStatusComponent_BP_Xenomorph_Queen_C"
    xenomorph_reaper_surface: str = "/Game/Aberration/CoreBlueprints/DinoCharacterStatusComponent_BP_Xenomorph_Reaper_Surface.DinoCharacterStatusComponent_BP_Xenomorph_Reaper_Surface_C"
    xenomorph_reaper_surface_alpha: str = "/Game/Aberration/CoreBlueprints/DinoCharacterStatusComponent_BP_Xenomorph_Reaper_Surface_Alpha.DinoCharacterStatusComponent_BP_Xenomorph_Reaper_Surface_Alpha_C"
    cave_wolf: str = "/Game/Aberration/Dinos/CaveWolf/DinoCharacterStatusComponent_BP_CaveWolf.DinoCharacterStatusComponent_BP_CaveWolf_C"
    light_bug: str = "/Game/Aberration/Dinos/Lightbug/DinoCharacterStatusComponent_BP_LightBug.DinoCharacterStatusComponent_BP_LightBug_C"
    rock_drake: str = "/Game/Aberration/Dinos/RockDrake/DinoCharacterStatusComponent_BP_RockDrake.DinoCharacterStatusComponent_BP_RockDrake_C"
    draco_umbra_lumina: str = "/Game/Dragontopia/Dragons/Eclipsar/Lumina/DinoCharacterStatusComponent_BP_Draco_Umbra_Lumina.DinoCharacterStatusComponent_BP_Draco_Umbra_Lumina_C"
    drone: str = "/Game/EndGame/Dinos/Drone/DinoCharacterStatusComponent_BP_Drone.DinoCharacterStatusComponent_BP_Drone_C"
    end_tank: str = "/Game/EndGame/Dinos/Tank/DinoCharacterStatusComponent_BP_EndTank.DinoCharacterStatusComponent_BP_EndTank_C"
    enforcer: str = "/Game/Extinction/CoreBlueprints/DinoCharacterStatusComponent_BP_Enforcer.DinoCharacterStatusComponent_BP_Enforcer_C"
    gacha: str = "/Game/Extinction/CoreBlueprints/DinoCharacterStatusComponent_BP_Gacha.DinoCharacterStatusComponent_BP_Gacha_C"
    gas_bag: str = "/Game/Extinction/CoreBlueprints/DinoCharacterStatusComponent_BP_GasBag.DinoCharacterStatusComponent_BP_GasBag_C"
    gigant_corrupt: str = "/Game/Extinction/CoreBlueprints/DinoCharacterStatusComponent_BP_Gigant_Corrupt.DinoCharacterStatusComponent_BP_Gigant_Corrupt_C"
    mega_rex_corrupted: str = "/Game/Extinction/CoreBlueprints/DinoCharacterStatusComponent_BP_MegaRex_Corrupted.DinoCharacterStatusComponent_BP_MegaRex_Corrupted_C"
    owl: str = "/Game/Extinction/CoreBlueprints/DinoCharacterStatusComponent_BP_Owl.DinoCharacterStatusComponent_BP_Owl_C"
    reaper_corrupt: str = "/Game/Extinction/CoreBlueprints/DinoCharacterStatusComponent_BP_Reaper_Corrupt.DinoCharacterStatusComponent_BP_Reaper_Corrupt_C"
    scout: str = "/Game/Extinction/CoreBlueprints/DinoCharacterStatusComponent_BP_Scout.DinoCharacterStatusComponent_BP_Scout_C"
    andrewsarchus: str = "/Game/Fjordur/Dinos/Andrewsarchus/DinoCharacterStatusComponent_BP_Andrewsarchus.DinoCharacterStatusComponent_BP_Andrewsarchus_C"
    desmodus: str = "/Game/Fjordur/Dinos/Desmodus/DinoCharacterStatusComponent_BP_Desmodus.DinoCharacterStatusComponent_BP_Desmodus_C"
    bog_spider: str = "/Game/Genesis/CoreBlueprints/DinoCharacterStatusComponent_BP_BogSpider.DinoCharacterStatusComponent_BP_BogSpider_C"
    cherufe: str = "/Game/Genesis/CoreBlueprints/DinoCharacterStatusComponent_BP_Cherufe.DinoCharacterStatusComponent_BP_Cherufe_C"
    insect_swarm: str = "/Game/Genesis/CoreBlueprints/DinoCharacterStatusComponent_BP_InsectSwarm.DinoCharacterStatusComponent_BP_InsectSwarm_C"
    microbe_swarm: str = "/Game/Genesis/CoreBlueprints/DinoCharacterStatusComponent_BP_MicrobeSwarm.DinoCharacterStatusComponent_BP_MicrobeSwarm_C"
    space_whale: str = "/Game/Genesis/CoreBlueprints/DinoCharacterStatusComponent_BP_SpaceWhale.DinoCharacterStatusComponent_BP_SpaceWhale_C"
    giant_turtle: str = "/Game/Genesis/Dinos/GiantTurtle/DinoCharacterStatusComponent_BP_GiantTurtle.DinoCharacterStatusComponent_BP_GiantTurtle_C"
    milk_glider: str = "/Game/Genesis2/Dinos/MilkGlider/DinoCharacterStatusComponent_BP_MilkGlider.DinoCharacterStatusComponent_BP_MilkGlider_C"
    angel_fox: str = "/Game/LostColony/Dinos/AngelFox/DinoCharacterStatusComponent_BP_AngelFox.DinoCharacterStatusComponent_BP_AngelFox_C"
    boss_bat: str = "/Game/LostColony/Dinos/BossBat/DinoCharacterStatusComponent_BP_BossBat.DinoCharacterStatusComponent_BP_BossBat_C"
    devil_fox: str = "/Game/LostColony/Dinos/DevilFox/DinoCharacterStatusComponent_BP_DevilFox.DinoCharacterStatusComponent_BP_DevilFox_C"
    lcp: str = "/Game/LostColony/Dinos/LostChargePet/DinoCharacterStatusComponent_BP_LCP.DinoCharacterStatusComponent_BP_LCP_C"
    flyer_ride_snow_dragon: str = "/Game/LostColony/Dinos/SnowDragon/DinoCharacterStatusComponent_BP_FlyerRide_SnowDragon.DinoCharacterStatusComponent_BP_FlyerRide_SnowDragon_C"
    mega_snow_monster: str = "/Game/LostColony/Dinos/SnowMonster/DinoCharacterStatusComponent_BP_MegaSnowMonster.DinoCharacterStatusComponent_BP_MegaSnowMonster_C"
    snow_monster: str = "/Game/LostColony/Dinos/SnowMonster/DinoCharacterStatusComponent_BP_SnowMonster.DinoCharacterStatusComponent_BP_SnowMonster_C"
    thrall_base: str = "/Game/LostColony/Dinos/Thrall/Components/DinoCharacterStatusComponent_BP_Thrall_Base.DinoCharacterStatusComponent_BP_Thrall_Base_C"
    young_ice_fox: str = "/Game/LostColony/Dinos/YoungIceFox/DinoCharacterStatusComponent_BP_YoungIceFox.DinoCharacterStatusComponent_BP_YoungIceFox_C"
    zombie_bloated: str = "/Game/LostColony/Dinos/Zombie/DinoCharacterStatusComponent_BP_Zombie_Bloated.DinoCharacterStatusComponent_BP_Zombie_Bloated_C"
    zombie_hulking: str = "/Game/LostColony/Dinos/Zombie/DinoCharacterStatusComponent_BP_Zombie_Hulking.DinoCharacterStatusComponent_BP_Zombie_Hulking_C"
    zombie_hulking_mega: str = "/Game/LostColony/Dinos/Zombie/DinoCharacterStatusComponent_BP_Zombie_Hulking_Mega.DinoCharacterStatusComponent_BP_Zombie_Hulking_Mega_C"
    zombie_skinny: str = "/Game/LostColony/Dinos/Zombie/DinoCharacterStatusComponent_BP_Zombie_Skinny.DinoCharacterStatusComponent_BP_Zombie_Skinny_C"
    oasisaur: str = "/Game/Packs/Frontier/Dinos/Oasisaur/DinoCharacterStatusComponent_BP_Oasisaur.DinoCharacterStatusComponent_BP_Oasisaur_C"
    train: str = "/Game/Packs/Frontier/Dinos/Train/DinoCharacterStatusComponent_BP_Train.DinoCharacterStatusComponent_BP_Train_C"
    helper_bot: str = "/Game/Packs/Steampunk/Dinos/HelperBot/DinoCharacterStatusComponent_BP_HelperBot.DinoCharacterStatusComponent_BP_HelperBot_C"
    jumping_spider: str = "/Game/Packs/Steampunk/Dinos/JumpingSpider/DinoCharacterStatusComponent_BP_JumpingSpider.DinoCharacterStatusComponent_BP_JumpingSpider_C"
    zeppelin: str = "/Game/Packs/Steampunk/Dinos/Zeppelin/DinoCharacterStatusComponent_BP_Zeppelin.DinoCharacterStatusComponent_BP_Zeppelin_C"
    axolotl_small: str = "/Game/Packs/TidesOfFortune/Dinos/Axolotl/Axolotl_Small/DinoCharacterStatusComponent_BP_Axolotl_Small.DinoCharacterStatusComponent_BP_Axolotl_Small_C"
    paleoctopus: str = "/Game/Packs/TidesOfFortune/Dinos/Paleoctopus/DinoCharacterStatusComponent_BP_Paleoctopus.DinoCharacterStatusComponent_BP_Paleoctopus_C"
    parrot: str = "/Game/Packs/TidesOfFortune/Dinos/Parrot/DinoCharacterStatusComponent_BP_Parrot.DinoCharacterStatusComponent_BP_Parrot_C"
    doggo: str = "/Game/Packs/Wasteland/Dinos/Doggo/DinoCharacterStatusComponent_BP_Doggo.DinoCharacterStatusComponent_BP_Doggo_C"
    car: str = "/Game/Packs/Wasteland/Vehicles/Car/DinoCharacterStatusComponent_BP_Car.DinoCharacterStatusComponent_BP_Car_C"
    allo: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Allo.DinoCharacterStatusComponent_BP_Allo_C"
    alpha_m_ega: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_AlphaMEga.DinoCharacterStatusComponent_BP_AlphaMega_C"
    angler: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Angler.DinoCharacterStatusComponent_BP_Angler_C"
    ankylo: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Ankylo.DinoCharacterStatusComponent_BP_Ankylo_C"
    ant: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Ant.DinoCharacterStatusComponent_BP_Ant_C"
    archa: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Archa.DinoCharacterStatusComponent_BP_Archa_C"
    argent: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Argent.DinoCharacterStatusComponent_BP_Argent_C"
    arthro: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Arthro.DinoCharacterStatusComponent_BP_Arthro_C"
    baryonyx: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Baryonyx.DinoCharacterStatusComponent_BP_Baryonyx_C"
    bat: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Bat.DinoCharacterStatusComponent_BP_Bat_C"
    beaver: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Beaver.DinoCharacterStatusComponent_BP_Beaver_C"
    beetle: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Beetle.DinoCharacterStatusComponent_BP_Beetle_C"
    bigfoot: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Bigfoot.DinoCharacterStatusComponent_BP_Bigfoot_C"
    boa_frill: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_BoaFrill.DinoCharacterStatusComponent_BP_BoaFrill_C"
    camel: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Camel.DinoCharacterStatusComponent_BP_Camel_C"
    carcha: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Carcha.DinoCharacterStatusComponent_BP_Carcha_C"
    carno: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Carno.DinoCharacterStatusComponent_BP_Carno_C"
    cnidaria: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Cnidaria.DinoCharacterStatusComponent_BP_Cnidaria_C"
    coel: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Coel.DinoCharacterStatusComponent_BP_Coel_C"
    compy: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Compy.DinoCharacterStatusComponent_BP_Compy_C"
    daeodon: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Daeodon.DinoCharacterStatusComponent_BP_Daeodon_C"
    dilo: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Dilo.DinoCharacterStatusComponent_BP_Dilo_C"
    dimetrodon: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Dimetrodon.DinoCharacterStatusComponent_BP_Dimetrodon_C"
    dimorph: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Dimorph.DinoCharacterStatusComponent_BP_Dimorph_C"
    diplocaulus: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Diplocaulus.DinoCharacterStatusComponent_BP_Diplocaulus_C"
    diplodocus: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Diplodocus.DinoCharacterStatusComponent_BP_Diplodocus_C"
    direbear: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Direbear.DinoCharacterStatusComponent_BP_Direbear_C"
    direwolf: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Direwolf.DinoCharacterStatusComponent_BP_Direwolf_C"
    dodo: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Dodo.DinoCharacterStatusComponent_BP_Dodo_C"
    dodo_rex: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_DodoRex.DinoCharacterStatusComponent_BP_DodoRex_C"
    doed: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Doed.DinoCharacterStatusComponent_BP_Doed_C"
    dolphin: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Dolphin.DinoCharacterStatusComponent_BP_Dolphin_C"
    dragonfly: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Dragonfly.DinoCharacterStatusComponent_BP_Dragonfly_C"
    dunkle: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Dunkle.DinoCharacterStatusComponent_BP_Dunkle_C"
    eel: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Eel.DinoCharacterStatusComponent_BP_Eel_C"
    equus: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Equus.DinoCharacterStatusComponent_BP_Equus_C"
    flying_ant: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_FlyingAnt.DinoCharacterStatusComponent_BP_FlyingAnt_C"
    galli: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Galli.DinoCharacterStatusComponent_BP_Galli_C"
    gigant: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Gigant.DinoCharacterStatusComponent_BP_Gigant_C"
    griffin: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Griffin.DinoCharacterStatusComponent_BP_Griffin_C"
    hesperornis: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Hesperornis.DinoCharacterStatusComponent_BP_Hesperornis_C"
    hyaenodon: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Hyaenodon.DinoCharacterStatusComponent_BP_Hyaenodon_C"
    ice_jumper: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_IceJumper.DinoCharacterStatusComponent_BP_IceJumper_C"
    ichthyornis: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Ichthyornis.DinoCharacterStatusComponent_BP_Ichthyornis_C"
    iguanodon: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Iguanodon.DinoCharacterStatusComponent_BP_Iguanodon_C"
    kairuku: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Kairuku.DinoCharacterStatusComponent_BP_Kairuku_C"
    kaprosuchus: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Kaprosuchus.DinoCharacterStatusComponent_BP_Kaprosuchus_C"
    kentro: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Kentro.DinoCharacterStatusComponent_BP_Kentro_C"
    liopleurodon: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Liopleurodon.DinoCharacterStatusComponent_BP_Liopleurodon_C"
    lystro: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Lystro.DinoCharacterStatusComponent_BP_Lystro_C"
    mammoth: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Mammoth.DinoCharacterStatusComponent_BP_Mammoth_C"
    manta: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Manta.DinoCharacterStatusComponent_BP_Manta_C"
    mega: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Mega.DinoCharacterStatusComponent_BP_Mega_C"
    mega_carno: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_MegaCarno.DinoCharacterStatusComponent_BP_MegaCarno_C"
    mega_raptor: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_MegaRaptor.DinoCharacterStatusComponent_BP_MegaRaptor_C"
    mega_rex: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_MegaRex.DinoCharacterStatusComponent_BP_MegaRex_C"
    megalania: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Megalania.DinoCharacterStatusComponent_BP_Megalania_C"
    megatherium: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Megatherium.DinoCharacterStatusComponent_BP_Megatherium_C"
    microraptor: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Microraptor.DinoCharacterStatusComponent_BP_Microraptor_C"
    monkey: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Monkey.DinoCharacterStatusComponent_BP_Monkey_C"
    moschops: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Moschops.DinoCharacterStatusComponent_BP_Moschops_C"
    motorboat: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Motorboat.DinoCharacterStatusComponent_BP_Motorboat_C"
    otter: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Otter.DinoCharacterStatusComponent_BP_Otter_C"
    oviraptor: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Oviraptor.DinoCharacterStatusComponent_BP_Oviraptor_C"
    pachy: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Pachy.DinoCharacterStatusComponent_BP_Pachy_C"
    pachyrhino: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Pachyrhino.DinoCharacterStatusComponent_BP_Pachyrhino_C"
    para: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Para.DinoCharacterStatusComponent_BP_Para_C"
    paracer: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Paracer.DinoCharacterStatusComponent_BP_Paracer_C"
    pela: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Pela.DinoCharacterStatusComponent_BP_Pela_C"
    phiomia: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Phiomia.DinoCharacterStatusComponent_BP_Phiomia_C"
    phoenix: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Phoenix.DinoCharacterStatusComponent_BP_Phoenix_C"
    piranha: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Piranha.DinoCharacterStatusComponent_BP_Piranha_C"
    plesiosaur: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Plesiosaur.DinoCharacterStatusComponent_BP_Plesiosaur_C"
    proc: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Proc.DinoCharacterStatusComponent_BP_Proc_C"
    ptero: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Ptero.DinoCharacterStatusComponent_BP_Ptero_C"
    queen_bee: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_QueenBee.DinoCharacterStatusComponent_BP_QueenBee_C"
    quetz: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Quetz.DinoCharacterStatusComponent_BP_Quetz_C"
    raft: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Raft.DinoCharacterStatusComponent_BP_Raft_C"
    raptor: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Raptor.DinoCharacterStatusComponent_BP_Raptor_C"
    rex: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Rex.DinoCharacterStatusComponent_BP_Rex_C"
    rhino: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Rhino.DinoCharacterStatusComponent_BP_Rhino_C"
    saber: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Saber.DinoCharacterStatusComponent_BP_Saber_C"
    salmon: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Salmon.DinoCharacterStatusComponent_BP_Salmon_C"
    sarco: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Sarco.DinoCharacterStatusComponent_BP_Sarco_C"
    sauropod: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Sauropod.DinoCharacterStatusComponent_BP_Sauropod_C"
    scorpion: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Scorpion.DinoCharacterStatusComponent_BP_Scorpion_C"
    sheep: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Sheep.DinoCharacterStatusComponent_BP_Sheep_C"
    spider: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Spider.DinoCharacterStatusComponent_BP_Spider_C"
    spindles: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Spindles.DinoCharacterStatusComponent_BP_Spindles_C"
    spino: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Spino.DinoCharacterStatusComponent_BP_Spino_C"
    stag: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Stag.DinoCharacterStatusComponent_BP_Stag_C"
    stego: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Stego.DinoCharacterStatusComponent_BP_Stego_C"
    tape: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Tape.DinoCharacterStatusComponent_BP_Tape_C"
    terror_bird: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_TerrorBird.DinoCharacterStatusComponent_BP_TerrorBird_C"
    therizino: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Therizino.DinoCharacterStatusComponent_BP_Therizino_C"
    thylaco: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Thylaco.DinoCharacterStatusComponent_BP_Thylaco_C"
    titanosaur: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Titanosaur.DinoCharacterStatusComponent_BP_Titanosaur_C"
    toad: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Toad.DinoCharacterStatusComponent_BP_Toad_C"
    trike: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Trike.DinoCharacterStatusComponent_BP_Trike_C"
    turtle: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Turtle.DinoCharacterStatusComponent_BP_Turtle_C"
    tuso: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Tuso.DinoCharacterStatusComponent_BP_Tuso_C"
    yeti: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Yeti.DinoCharacterStatusComponent_BP_Yeti_C"
    yutyrannus: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Yutyrannus.DinoCharacterStatusComponent_BP_Yutyrannus_C"
    zomdod: str = "/Game/PrimalEarth/CoreBlueprints/DinoCharacterStatusComponent_BP_Zomdod.DinoCharacterStatusComponent_BP_Zomdod_C"
    mega_tuso: str = "/Game/PrimalEarth/CoreBlueprints/Mega_DinoCharacterStatusComponent_BP_Tuso.Mega_DinoCharacterStatusComponent_BP_Tuso_C"
    achatina: str = "/Game/PrimalEarth/Dinos/Achatina/DinoCharacterStatusComponent_BP_Achatina.DinoCharacterStatusComponent_BP_Achatina_C"
    basil: str = "/Game/PrimalEarth/Dinos/Basilosaurus/DinoCharacterStatusComponent_BP_Basil.DinoCharacterStatusComponent_BP_Basil_C"
    chalico: str = "/Game/PrimalEarth/Dinos/Chalicotherium/DinoCharacterStatusComponent_BP_Chalico.DinoCharacterStatusComponent_BP_Chalico_C"
    leedsichthys: str = "/Game/PrimalEarth/Dinos/Leedsichthys/DinoCharacterStatusComponent_BP_Leedsichthys.DinoCharacterStatusComponent_BP_Leedsichthys_C"
    megalosaurus: str = "/Game/PrimalEarth/Dinos/Megalosaurus/DinoCharacterStatusComponent_BP_Megalosaurus.DinoCharacterStatusComponent_BP_Megalosaurus_C"
    mosasaur: str = "/Game/PrimalEarth/Dinos/Mosasaurus/DinoCharacterStatusComponent_BP_Mosasaur.DinoCharacterStatusComponent_BP_Mosasaur_C"
    mosasaur_mega: str = "/Game/PrimalEarth/Dinos/Mosasaurus/DinoCharacterStatusComponent_BP_Mosasaur_Mega.DinoCharacterStatusComponent_BP_Mosasaur_Mega_C"
    pegomastax: str = "/Game/PrimalEarth/Dinos/Pegomastax/DinoCharacterStatusComponent_BP_Pegomastax.DinoCharacterStatusComponent_BP_Pegomastax_C"
    purlovia: str = "/Game/PrimalEarth/Dinos/Purlovia/DinoCharacterStatusComponent_BP_Purlovia.DinoCharacterStatusComponent_BP_Purlovia_C"
    purlovia_polar: str = "/Game/PrimalEarth/Dinos/Purlovia/DinoCharacterStatusComponent_BP_Purlovia_Polar.DinoCharacterStatusComponent_BP_Purlovia_Polar_C"
    rhynio: str = "/Game/PrimalEarth/Dinos/Rhyniognatha/DinoCharacterStatusComponent_BP_Rhynio.DinoCharacterStatusComponent_BP_Rhynio_C"
    ammonite: str = "/Game/PrimalEarth/Dinos/Trilobite/DinoCharacterStatusComponent_BP_Ammonite.DinoCharacterStatusComponent_BP_Ammonite_C"
    leech: str = "/Game/PrimalEarth/Dinos/Trilobite/DinoCharacterStatusComponent_BP_Leech.DinoCharacterStatusComponent_BP_Leech_C"
    leech_diseased: str = "/Game/PrimalEarth/Dinos/Trilobite/DinoCharacterStatusComponent_BP_Leech_Diseased.DinoCharacterStatusComponent_BP_Leech_Diseased_C"
    trilobite: str = "/Game/PrimalEarth/Dinos/Trilobite/DinoCharacterStatusComponent_BP_Trilobite.DinoCharacterStatusComponent_BP_Trilobite_C"
    troodon: str = "/Game/PrimalEarth/Dinos/Troodon/DinoCharacterStatusComponent_BP_Troodon.DinoCharacterStatusComponent_BP_Troodon_C"
    deathworm: str = "/Game/ScorchedEarth/Dinos/Deathworm/DinoCharacterStatusComponent_BP_Deathworm.DinoCharacterStatusComponent_BP_Deathworm_C"
    deathworm_alpha: str = "/Game/ScorchedEarth/Dinos/Deathworm/DinoCharacterStatusComponent_BP_Deathworm_Alpha.DinoCharacterStatusComponent_BP_Deathworm_Alpha_C"
    dodo_wyvern: str = "/Game/ScorchedEarth/Dinos/DodoWyvern/DinoCharacterStatusComponent_BP_DodoWyvern.DinoCharacterStatusComponent_BP_DodoWyvern_C"
    jerboa: str = "/Game/ScorchedEarth/Dinos/Jerboa/DinoCharacterStatusComponent_BP_Jerboa.DinoCharacterStatusComponent_BP_Jerboa_C"
    jug_bug: str = "/Game/ScorchedEarth/Dinos/JugBug/DinoCharacterStatusComponent_BP_JugBug.DinoCharacterStatusComponent_BP_JugBug_C"
    deathworm_minion: str = "/Game/ScorchedEarth/Dinos/Manticore/Minions/DinoCharacterStatusComponent_BP_Deathworm_Minion.DinoCharacterStatusComponent_BP_Deathworm_Minion_C"
    mantis: str = "/Game/ScorchedEarth/Dinos/Mantis/DinoCharacterStatusComponent_BP_Mantis.DinoCharacterStatusComponent_BP_Mantis_C"
    moth: str = "/Game/ScorchedEarth/Dinos/Moth/DinoCharacterStatusComponent_BP_Moth.DinoCharacterStatusComponent_BP_Moth_C"
    rock_golem: str = "/Game/ScorchedEarth/Dinos/RockGolem/DinoCharacterStatusComponent_BP_RockGolem.DinoCharacterStatusComponent_BP_RockGolem_C"
    rubble_golem: str = "/Game/ScorchedEarth/Dinos/RockGolem/DinoCharacterStatusComponent_BP_RubbleGolem.DinoCharacterStatusComponent_BP_RubbleGolem_C"
    spiney_lizard: str = "/Game/ScorchedEarth/Dinos/SpineyLizard/DinoCharacterStatusComponent_BP_SpineyLizard.DinoCharacterStatusComponent_BP_SpineyLizard_C"
    vulture: str = "/Game/ScorchedEarth/Dinos/Vulture/DinoCharacterStatusComponent_BP_Vulture.DinoCharacterStatusComponent_BP_Vulture_C"
    mega_wyvern: str = "/Game/ScorchedEarth/Dinos/Wyvern/DinoCharacterStatusComponent_BP_MegaWyvern.DinoCharacterStatusComponent_BP_MegaWyvern_C"
    wyvern: str = "/Game/ScorchedEarth/Dinos/Wyvern/DinoCharacterStatusComponent_BP_Wyvern.DinoCharacterStatusComponent_BP_Wyvern_C"
    brig_ship: str = "/Game/Water/Vessels/Brig/DinoCharacterStatusComponent_BP_BrigShip.DinoCharacterStatusComponent_BP_BrigShip_C"
    brig_ship_player_following_miniboss: str = "/Game/Water/Vessels/Brig/DinoCharacterStatusComponent_BP_BrigShipPlayerFollowing_Miniboss.DinoCharacterStatusComponent_BP_BrigShipPlayerFollowing_Miniboss_C"
    sloop_ship: str = "/Game/Water/Vessels/Sloop/DinoCharacterStatusComponent_BP_SloopShip.DinoCharacterStatusComponent_BP_SloopShip_C"

    all_bps = [acrocanthosaurus, archelon_asa, bison, boaratos, cat, ceratosaurus_asa, concavenator,
               cryolophosaurus, dark_pegasus, deino_asa, deinotherium_asa, dreadnoughtus, fasola, fire_lion,
               gigantoraptor, helicoprion, jackalope, val_megaraptor, shastasaurus, shoulder_dragon, s_bear,
               xiph_asa, yi_ling, basilisk, basilisk_alpha, cave_crab, cave_crab_alpha, chupa_cabra,
               lantern_bird, lantern_goat, lantern_lizard, lantern_pug, mole_rat, pteroteuthis,
               xenomorph_chupa, xenomorph_queen, xenomorph_reaper_surface, xenomorph_reaper_surface_alpha,
               cave_wolf, light_bug, rock_drake, draco_umbra_lumina, drone, end_tank, enforcer, gacha,
               gas_bag, gigant_corrupt, mega_rex_corrupted, owl, reaper_corrupt, scout, andrewsarchus,
               desmodus, bog_spider, cherufe, insect_swarm, microbe_swarm, space_whale, giant_turtle,
               milk_glider, angel_fox, boss_bat, devil_fox, lcp, flyer_ride_snow_dragon, mega_snow_monster,
               snow_monster, thrall_base, young_ice_fox, zombie_bloated, zombie_hulking, zombie_hulking_mega,
               zombie_skinny, oasisaur, train, helper_bot, jumping_spider, zeppelin, axolotl_small,
               paleoctopus, parrot, doggo, car, allo, alpha_m_ega, angler, ankylo, ant, archa, argent, arthro,
               baryonyx, bat, beaver, beetle, bigfoot, boa_frill, camel, carcha, carno, cnidaria, coel, compy,
               daeodon, dilo, dimetrodon, dimorph, diplocaulus, diplodocus, direbear, direwolf, dodo,
               dodo_rex, doed, dolphin, dragonfly, dunkle, eel, equus, flying_ant, galli, gigant, griffin,
               hesperornis, hyaenodon, ice_jumper, ichthyornis, iguanodon, kairuku, kaprosuchus, kentro,
               liopleurodon, lystro, mammoth, manta, mega, mega_carno, mega_raptor, mega_rex, megalania,
               megatherium, microraptor, monkey, moschops, motorboat, otter, oviraptor, pachy, pachyrhino,
               para, paracer, pela, phiomia, phoenix, piranha, plesiosaur, proc, ptero, queen_bee, quetz,
               raft, raptor, rex, rhino, saber, salmon, sarco, sauropod, scorpion, sheep, spider, spindles,
               spino, stag, stego, tape, terror_bird, therizino, thylaco, titanosaur, toad, trike, turtle,
               tuso, yeti, yutyrannus, zomdod, mega_tuso, achatina, basil, chalico, leedsichthys,
               megalosaurus, mosasaur, mosasaur_mega, pegomastax, purlovia, purlovia_polar, rhynio, ammonite,
               leech, leech_diseased, trilobite, troodon, deathworm, deathworm_alpha, dodo_wyvern, jerboa,
               jug_bug, deathworm_minion, mantis, moth, rock_golem, rubble_golem, spiney_lizard, vulture,
               mega_wyvern, wyvern, brig_ship, brig_ship_player_following_miniboss, sloop_ship]

class InventoryComponents:
    acrocanthosaurus: str = "/Game/ASA/Dinos/Acrocanthosaurus/DinoTamedInventoryComponent_Acrocanthosaurus.DinoTamedInventoryComponent_Acrocanthosaurus_C"
    archelon_asa: str = "/Game/ASA/Dinos/Archelon/Dinos/DinoTamedInventoryComponent_Archelon_ASA.DinoTamedInventoryComponent_Archelon_ASA_C"
    bison: str = "/Game/ASA/Dinos/Bison/DinoTamedInventoryComponent_Bison.DinoTamedInventoryComponent_Bison_C"
    boaratos: str = "/Game/ASA/Dinos/Boaratos/DinoTamedInventoryComponent_Boaratos.DinoTamedInventoryComponent_Boaratos_C"
    cat: str = "/Game/ASA/Dinos/Cat/DinoTamedInventoryComponent_Cat.DinoTamedInventoryComponent_Cat_C"
    cryolophosaurus: str = "/Game/ASA/Dinos/Cryolophosaurus/DinoTamedInventoryComponent_Cryolophosaurus.DinoTamedInventoryComponent_Cryolophosaurus_C"
    dark_pegasus: str = "/Game/ASA/Dinos/DarkPegasus/DinoTamedInventoryComponent_DarkPegasus.DinoTamedInventoryComponent_DarkPegasus_C"
    deino_asa: str = "/Game/ASA/Dinos/Deinosuchus/DinoTamedInventoryComponent_Deino_ASA.DinoTamedInventoryComponent_Deino_ASA_C"
    dreadnoughtus: str = "/Game/ASA/Dinos/Dreadnoughtus/DinoTamedInventoryComponent_Dreadnoughtus.DinoTamedInventoryComponent_Dreadnoughtus_C"
    fasola: str = "/Game/ASA/Dinos/Fasolasuchus/DinoTamedInventoryComponent_Fasola.DinoTamedInventoryComponent_Fasola_C"
    fire_lion: str = "/Game/ASA/Dinos/FireLion/DinoTamedInventoryComponent_FireLion.DinoTamedInventoryComponent_FireLion_C"
    gigantoraptor: str = "/Game/ASA/Dinos/Gigantoraptor/DinoTamedInventoryComponent_Gigantoraptor.DinoTamedInventoryComponent_Gigantoraptor_C"
    helicoprion: str = "/Game/ASA/Dinos/Helicoprion/DinoTamedInventoryComponent_Helicoprion.DinoTamedInventoryComponent_Helicoprion_C"
    val_megaraptor: str = "/Game/ASA/Dinos/Megaraptor/DinoTamedInventoryComponent_ValMegaraptor.DinoTamedInventoryComponent_ValMegaraptor_C"
    shasta: str = "/Game/ASA/Dinos/Shastasaurus/DinoTamedInventoryComponent_Shasta.DinoTamedInventoryComponent_Shasta_C"
    shoulder_dragon_autumn: str = "/Game/ASA/Dinos/ShoulderDragon/Variants/Autumn/DinoTamedInventoryComponent_ShoulderDragon_Autumn.DinoTamedInventoryComponent_ShoulderDragon_Autumn_C"
    shoulder_dragon_spring: str = "/Game/ASA/Dinos/ShoulderDragon/Variants/Spring/DinoTamedInventoryComponent_ShoulderDragon_Spring.DinoTamedInventoryComponent_ShoulderDragon_Spring_C"
    shoulder_dragon_summer: str = "/Game/ASA/Dinos/ShoulderDragon/Variants/Summer/DinoTamedInventoryComponent_ShoulderDragon_Summer.DinoTamedInventoryComponent_ShoulderDragon_Summer_C"
    shoulder_dragon_winter: str = "/Game/ASA/Dinos/ShoulderDragon/Variants/Winter/DinoTamedInventoryComponent_ShoulderDragon_Winter.DinoTamedInventoryComponent_ShoulderDragon_Winter_C"
    spirit_bear: str = "/Game/ASA/Dinos/SpiritBear/Gameplay/DinoTamedInventoryComponent_SpiritBear.DinoTamedInventoryComponent_SpiritBear_C"
    dino_wild_inventory_component_s_bear: str = "/Game/ASA/Dinos/SpiritBear/Gameplay/DinoWildInventoryComponent_SBear.DinoWildInventoryComponent_SBear_C"
    yi_ling: str = "/Game/ASA/Dinos/YiLing/DinoTamedInventoryComponent_YiLing.DinoTamedInventoryComponent_YiLing_C"
    basilisk: str = "/Game/Aberration/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Basilisk.DinoTamedInventoryComponent_Basilisk_C"
    lantern_bird: str = "/Game/Aberration/CoreBlueprints/Inventories/DinoTamedInventoryComponent_LanternBird.DinoTamedInventoryComponent_LanternBird_C"
    lantern_goat: str = "/Game/Aberration/CoreBlueprints/Inventories/DinoTamedInventoryComponent_LanternGoat.DinoTamedInventoryComponent_LanternGoat_C"
    lantern_lizard: str = "/Game/Aberration/CoreBlueprints/Inventories/DinoTamedInventoryComponent_LanternLizard.DinoTamedInventoryComponent_LanternLizard_C"
    lantern_pug: str = "/Game/Aberration/CoreBlueprints/Inventories/DinoTamedInventoryComponent_LanternPug.DinoTamedInventoryComponent_LanternPug_C"
    mole_rat: str = "/Game/Aberration/CoreBlueprints/Inventories/DinoTamedInventoryComponent_MoleRat.DinoTamedInventoryComponent_MoleRat_C"
    cave_wolf: str = "/Game/Aberration/Dinos/CaveWolf/DinoTamedInventoryComponent_CaveWolf.DinoTamedInventoryComponent_CaveWolf_C"
    crab: str = "/Game/Aberration/Dinos/Crab/DinoTamedInventoryComponent_Crab.DinoTamedInventoryComponent_Crab_C"
    nameless: str = "/Game/Aberration/Dinos/Nameless/DinoTamedInventoryComponent_Nameless.DinoTamedInventoryComponent_Nameless_C"
    rock_drake: str = "/Game/Aberration/Dinos/RockDrake/DinoTamedInventoryComponent_RockDrake.DinoTamedInventoryComponent_RockDrake_C"
    draco: str = "/Game/Dragontopia/Dragons/Base/DinoTamedInventoryComponent_BP_Draco.DinoTamedInventoryComponent_BP_Draco_C"
    enforcer: str = "/Game/Extinction/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Enforcer.DinoTamedInventoryComponent_Enforcer_C"
    gacha: str = "/Game/Extinction/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Gacha.DinoTamedInventoryComponent_Gacha_C"
    gas_bag: str = "/Game/Extinction/CoreBlueprints/Inventories/DinoTamedInventoryComponent_GasBag.DinoTamedInventoryComponent_GasBag_C"
    owl: str = "/Game/Extinction/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Owl.DinoTamedInventoryComponent_Owl_C"
    spindles: str = "/Game/Extinction/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Spindles.DinoTamedInventoryComponent_Spindles_C"
    ice_jumper: str = "/Game/Extinction/Dinos/IceJumper/DinoTamedInventoryComponent_IceJumper.DinoTamedInventoryComponent_IceJumper_C"
    desmodus: str = "/Game/Fjordur/Dinos/Desmodus/DinoTamedInventoryComponent_Desmodus.DinoTamedInventoryComponent_Desmodus_C"
    forge_capable_cherufe: str = "/Game/Genesis/CoreBlueprints/Inventories/DinoTamedInventoryComponent_ForgeCapable_Cherufe.DinoTamedInventoryComponent_ForgeCapable_Cherufe_C"
    milk_glider: str = "/Game/Genesis2/Dinos/MilkGlider/DinoTamedInventoryComponent_MilkGlider.DinoTamedInventoryComponent_MilkGlider_C"
    boss_bat: str = "/Game/LostColony/Dinos/BossBat/DinoTamedInventoryComponent_BossBat.DinoTamedInventoryComponent_BossBat_C"
    devil_fox: str = "/Game/LostColony/Dinos/DevilFox/DinoTamedInventoryComponent_DevilFox.DinoTamedInventoryComponent_DevilFox_C"
    lost_charge_pet: str = "/Game/LostColony/Dinos/LostChargePet/DinoTamedInventoryComponent_LostChargePet.DinoTamedInventoryComponent_LostChargePet_C"
    snow_dragon: str = "/Game/LostColony/Dinos/SnowDragon/DinoTamedInventoryComponent_SnowDragon.DinoTamedInventoryComponent_SnowDragon_C"
    snow_monster: str = "/Game/LostColony/Dinos/SnowMonster/DinoTamedInventoryComponent_SnowMonster.DinoTamedInventoryComponent_SnowMonster_C"
    thrall: str = "/Game/LostColony/Dinos/Thrall/Characters/Base/DinoTamedInventoryComponent_BP_Thrall.DinoTamedInventoryComponent_BP_Thrall_C"
    dino_companion_young_ice_fox: str = "/Game/LostColony/Dinos/YoungIceFox/DinoTamedInventoryComponent_DinoCompanion_YoungIceFox.DinoTamedInventoryComponent_DinoCompanion_YoungIceFox_C"
    oasisaur: str = "/Game/Packs/Frontier/Dinos/Oasisaur/DinoTamedInventoryComponent_Oasisaur.DinoTamedInventoryComponent_Oasisaur_C"
    train: str = "/Game/Packs/Frontier/Dinos/Train/DinoTamedInventoryComponent_BP_Train.DinoTamedInventoryComponent_BP_Train_C"
    helper_bot: str = "/Game/Packs/Steampunk/Dinos/HelperBot/DinoTamedInventoryComponent_HelperBot.DinoTamedInventoryComponent_HelperBot_C"
    jumping_spider: str = "/Game/Packs/Steampunk/Dinos/JumpingSpider/DinoTamedInventoryComponent_JumpingSpider.DinoTamedInventoryComponent_JumpingSpider_C"
    zeppelin: str = "/Game/Packs/Steampunk/Dinos/Zeppelin/DinoTamedInventoryComponent_Zeppelin.DinoTamedInventoryComponent_Zeppelin_C"
    axolotl_small: str = "/Game/Packs/TidesOfFortune/Dinos/Axolotl/Axolotl_Small/DinoTamedInventoryComponent_Axolotl_Small.DinoTamedInventoryComponent_Axolotl_Small_C"
    paleactopus: str = "/Game/Packs/TidesOfFortune/Dinos/Paleoctopus/DinoTamedInventory_Paleactopus.DinoTamedInventory_Paleactopus_C"
    parrot: str = "/Game/Packs/TidesOfFortune/Dinos/Parrot/DinoTamedInventoryComponent_Parrot.DinoTamedInventoryComponent_Parrot_C"
    dino_companion_doggo: str = "/Game/Packs/Wasteland/Dinos/Doggo/DinoTamedInventoryComponent_DinoCompanion_Doggo.DinoTamedInventoryComponent_DinoCompanion_Doggo_C"
    car: str = "/Game/Packs/Wasteland/Vehicles/Car/DinoTamedInventoryComponent_Car.DinoTamedInventoryComponent_Car_C"
    dino_drop_inventory_component_carnivore_large_allo: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoDropInventoryComponent_Carnivore_Large_Allo.DinoDropInventoryComponent_Carnivore_Large_Allo_C"
    dino_drop_inventory_component_carnivore_large_treasure: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoDropInventoryComponent_Carnivore_Large_Treasure.DinoDropInventoryComponent_Carnivore_Large_Treasure_C"
    dino_drop_inventory_component_carnivore_medium_treasure: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoDropInventoryComponent_Carnivore_Medium_Treasure.DinoDropInventoryComponent_Carnivore_Medium_Treasure_C"
    dino_drop_inventory_component_carnivore_small_otter: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoDropInventoryComponent_Carnivore_Small_Otter.DinoDropInventoryComponent_Carnivore_Small_Otter_C"
    angler: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Angler.DinoTamedInventoryComponent_Angler_C"
    ankylo: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Ankylo.DinoTamedInventoryComponent_Ankylo_C"
    archa: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Archa.DinoTamedInventoryComponent_Archa_C"
    argent: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Argent.DinoTamedInventoryComponent_Argent_C"
    arthro: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Arthro.DinoTamedInventoryComponent_Arthro_C"
    achatina: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_BP_Achatina.DinoTamedInventoryComponent_BP_Achatina_C"
    dino_tamed_inventory_component_bp_base: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_BP_Base.DinoTamedInventoryComponent_BP_Base_C"
    basilosaurus: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_BP_Basilosaurus.DinoTamedInventoryComponent_BP_Basilosaurus_C"
    bigfoot: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_BP_Bigfoot.DinoTamedInventoryComponent_BP_Bigfoot_C"
    lystro: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_BP_Lystro.DinoTamedInventoryComponent_BP_Lystro_C"
    tuso: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_BP_Tuso.DinoTamedInventoryComponent_BP_Tuso_C"
    baryonyx: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Baryonyx.DinoTamedInventoryComponent_Baryonyx_C"
    beaver: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Beaver.DinoTamedInventoryComponent_Beaver_C"
    beetle: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Beetle.DinoTamedInventoryComponent_Beetle_C"
    carcha: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Carcha.DinoTamedInventoryComponent_Carcha_C"
    carno: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Carno.DinoTamedInventoryComponent_Carno_C"
    carno_hyaenodon: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Carno_Hyaenodon.DinoTamedInventoryComponent_Carno_Hyaenodon_C"
    chalico: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Chalico.DinoTamedInventoryComponent_Chalico_C"
    compy: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Compy.DinoTamedInventoryComponent_Compy_C"
    daeodon: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Daeodon.DinoTamedInventoryComponent_Daeodon_C"
    dilo: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Dilo.DinoTamedInventoryComponent_Dilo_C"
    dimetrodon: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Dimetrodon.DinoTamedInventoryComponent_Dimetrodon_C"
    dimorph: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Dimorph.DinoTamedInventoryComponent_Dimorph_C"
    diplocaulus: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Diplocaulus.DinoTamedInventoryComponent_Diplocaulus_C"
    direbear: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Direbear.DinoTamedInventoryComponent_Direbear_C"
    direwolf: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Direwolf.DinoTamedInventoryComponent_Direwolf_C"
    dodo: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Dodo.DinoTamedInventoryComponent_Dodo_C"
    dodo_rex: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_DodoRex.DinoTamedInventoryComponent_DodoRex_C"
    doed: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Doed.DinoTamedInventoryComponent_Doed_C"
    dolphin: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Dolphin.DinoTamedInventoryComponent_Dolphin_C"
    dunkle: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Dunkle.DinoTamedInventoryComponent_Dunkle_C"
    equus: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Equus.DinoTamedInventoryComponent_Equus_C"
    galli: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Galli.DinoTamedInventoryComponent_Galli_C"
    gigant: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Gigant.DinoTamedInventoryComponent_Gigant_C"
    griffin: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Griffin.DinoTamedInventoryComponent_Griffin_C"
    hesperonis: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Hesperonis.DinoTamedInventoryComponent_Hesperonis_C"
    ice_wyvern: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_IceWyvern.DinoTamedInventoryComponent_IceWyvern_C"
    ichthyornis: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Ichthyornis.DinoTamedInventoryComponent_Ichthyornis_C"
    iguanodon: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Iguanodon.DinoTamedInventoryComponent_Iguanodon_C"
    jerboa: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Jerboa.DinoTamedInventoryComponent_Jerboa_C"
    kairuku: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Kairuku.DinoTamedInventoryComponent_Kairuku_C"
    kaprosuchus: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Kaprosuchus.DinoTamedInventoryComponent_Kaprosuchus_C"
    kentro: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Kentro.DinoTamedInventoryComponent_Kentro_C"
    liopleur: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Liopleur.DinoTamedInventoryComponent_Liopleur_C"
    mammoth: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Mammoth.DinoTamedInventoryComponent_Mammoth_C"
    mega: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Mega.DinoTamedInventoryComponent_Mega_C"
    megalosaurus: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Megalosaurus.DinoTamedInventoryComponent_Megalosaurus_C"
    megatherium: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Megatherium.DinoTamedInventoryComponent_Megatherium_C"
    microraptor: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Microraptor.DinoTamedInventoryComponent_Microraptor_C"
    monkey: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Monkey.DinoTamedInventoryComponent_Monkey_C"
    moschops: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Moschops.DinoTamedInventoryComponent_Moschops_C"
    oviraptor: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Oviraptor.DinoTamedInventoryComponent_Oviraptor_C"
    pachy: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Pachy.DinoTamedInventoryComponent_Pachy_C"
    pachyrhino: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Pachyrhino.DinoTamedInventoryComponent_Pachyrhino_C"
    para: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Para.DinoTamedInventoryComponent_Para_C"
    paracer: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Paracer.DinoTamedInventoryComponent_Paracer_C"
    pegomastax: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Pegomastax.DinoTamedInventoryComponent_Pegomastax_C"
    pelagornis: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Pelagornis.DinoTamedInventoryComponent_Pelagornis_C"
    phiomia: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Phiomia.DinoTamedInventoryComponent_Phiomia_C"
    phoenix: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Phoenix.DinoTamedInventoryComponent_Phoenix_C"
    plesio: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Plesio.DinoTamedInventoryComponent_Plesio_C"
    proc: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Proc.DinoTamedInventoryComponent_Proc_C"
    ptero: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Ptero.DinoTamedInventoryComponent_Ptero_C"
    purlovia: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Purlovia.DinoTamedInventoryComponent_Purlovia_C"
    quetz: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Quetz.DinoTamedInventoryComponent_Quetz_C"
    raptor: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Raptor.DinoTamedInventoryComponent_Raptor_C"
    rex: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Rex.DinoTamedInventoryComponent_Rex_C"
    rhino: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Rhino.DinoTamedInventoryComponent_Rhino_C"
    saber: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Saber.DinoTamedInventoryComponent_Saber_C"
    sarco: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Sarco.DinoTamedInventoryComponent_Sarco_C"
    sauro: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Sauro.DinoTamedInventoryComponent_Sauro_C"
    scorpion: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Scorpion.DinoTamedInventoryComponent_Scorpion_C"
    spider_s: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_SpiderS.DinoTamedInventoryComponent_SpiderS_C"
    spiney_beaver: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_SpineyBeaver.DinoTamedInventoryComponent_SpineyBeaver_C"
    spino: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Spino.DinoTamedInventoryComponent_Spino_C"
    stag: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Stag.DinoTamedInventoryComponent_Stag_C"
    stego: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Stego.DinoTamedInventoryComponent_Stego_C"
    tapejara: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Tapejara.DinoTamedInventoryComponent_Tapejara_C"
    terrorbird: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Terrorbird.DinoTamedInventoryComponent_Terrorbird_C"
    therizino: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Therizino.DinoTamedInventoryComponent_Therizino_C"
    thyla: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Thyla.DinoTamedInventoryComponent_Thyla_C"
    titan: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Titan.DinoTamedInventoryComponent_Titan_C"
    toad: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Toad.DinoTamedInventoryComponent_Toad_C"
    trike: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Trike.DinoTamedInventoryComponent_Trike_C"
    turtle: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Turtle.DinoTamedInventoryComponent_Turtle_C"
    wyvern: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_Wyvern.DinoTamedInventoryComponent_Wyvern_C"
    zom_wyvern: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoTamedInventoryComponent_ZomWyvern.DinoTamedInventoryComponent_ZomWyvern_C"
    dino_wild_inventory_component_pegomastax: str = "/Game/PrimalEarth/CoreBlueprints/Inventories/DinoWildInventoryComponent_Pegomastax.DinoWildInventoryComponent_Pegomastax_C"
    rhynio: str = "/Game/PrimalEarth/Dinos/Rhyniognatha/DinoTamedInventoryComponent_Rhynio.DinoTamedInventoryComponent_Rhynio_C"
    dino_inventory_component_motor_raft: str = "/Game/PrimalEarth/Items/Raft/DinoInventoryComponent_MotorRaft.DinoInventoryComponent_MotorRaft_C"
    camelsaurus: str = "/Game/ScorchedEarth/Dinos/Camelsaurus/DinoTamedInventoryComponent_Camelsaurus.DinoTamedInventoryComponent_Camelsaurus_C"
    mantis: str = "/Game/ScorchedEarth/Dinos/Mantis/DinoTamedInventoryComponent_Mantis.DinoTamedInventoryComponent_Mantis_C"
    moth: str = "/Game/ScorchedEarth/Dinos/Moth/DinoTamedInventoryComponent_Moth.DinoTamedInventoryComponent_Moth_C"
    rock_golem: str = "/Game/ScorchedEarth/Dinos/RockGolem/DinoTamedInventoryComponent_BP_RockGolem.DinoTamedInventoryComponent_BP_RockGolem_C"
    vulture: str = "/Game/ScorchedEarth/Dinos/Vulture/DinoTamedInventoryComponent_Vulture.DinoTamedInventoryComponent_Vulture_C"

    all_bps = [acrocanthosaurus, archelon_asa, bison, boaratos, cat, cryolophosaurus, dark_pegasus, deino_asa,
               dreadnoughtus, fasola, fire_lion, gigantoraptor, helicoprion, val_megaraptor, shasta,
               shoulder_dragon_autumn, shoulder_dragon_spring, shoulder_dragon_summer, shoulder_dragon_winter,
               spirit_bear, dino_wild_inventory_component_s_bear, yi_ling, basilisk, lantern_bird,
               lantern_goat, lantern_lizard, lantern_pug, mole_rat, cave_wolf, crab, nameless, rock_drake,
               draco, enforcer, gacha, gas_bag, owl, spindles, ice_jumper, desmodus, forge_capable_cherufe,
               milk_glider, boss_bat, devil_fox, lost_charge_pet, snow_dragon, snow_monster, thrall,
               dino_companion_young_ice_fox, oasisaur, train, helper_bot, jumping_spider, zeppelin,
               axolotl_small, paleactopus, parrot, dino_companion_doggo, car,
               dino_drop_inventory_component_carnivore_large_allo,
               dino_drop_inventory_component_carnivore_large_treasure,
               dino_drop_inventory_component_carnivore_medium_treasure,
               dino_drop_inventory_component_carnivore_small_otter, angler, ankylo, archa, argent, arthro,
               achatina, dino_tamed_inventory_component_bp_base, basilosaurus, bigfoot, lystro, tuso,
               baryonyx, beaver, beetle, carcha, carno, carno_hyaenodon, chalico, compy, daeodon, dilo,
               dimetrodon, dimorph, diplocaulus, direbear, direwolf, dodo, dodo_rex, doed, dolphin, dunkle,
               equus, galli, gigant, griffin, hesperonis, ice_wyvern, ichthyornis, iguanodon, jerboa, kairuku,
               kaprosuchus, kentro, liopleur, mammoth, mega, megalosaurus, megatherium, microraptor, monkey,
               moschops, oviraptor, pachy, pachyrhino, para, paracer, pegomastax, pelagornis, phiomia,
               phoenix, plesio, proc, ptero, purlovia, quetz, raptor, rex, rhino, saber, sarco, sauro,
               scorpion, spider_s, spiney_beaver, spino, stag, stego, tapejara, terrorbird, therizino, thyla,
               titan, toad, trike, turtle, wyvern, zom_wyvern, dino_wild_inventory_component_pegomastax,
               rhynio, dino_inventory_component_motor_raft, camelsaurus, mantis, moth, rock_golem, vulture]

class AIControllers:
    acro: str = "/Game/ASA/Dinos/Acrocanthosaurus/Acro_AIController_BP.Acro_AIController_BP_C"
    archelon_asa: str = "/Game/ASA/Dinos/Archelon/Dinos/Archelon_AIController_BP_ASA.Archelon_AIController_BP_ASA_C"
    bison: str = "/Game/ASA/Dinos/Bison/Bison_AIController_BP.Bison_AIController_BP_C"
    cat: str = "/Game/ASA/Dinos/Cat/Cat_AIController_BP.Cat_AIController_BP_C"
    cat_tamed: str = "/Game/ASA/Dinos/Cat/Cat_AIController_BP_Tamed.Cat_AIController_BP_Tamed_C"
    cerato_asa: str = "/Game/ASA/Dinos/Ceratosaurus/Dinos/Cerato_AIController_BP_ASA.Cerato_AIController_BP_ASA_C"
    cryolophosaurus: str = "/Game/ASA/Dinos/Cryolophosaurus/Cryolophosaurus_AIController_BP.Cryolophosaurus_AIController_BP_C"
    dark_pegasus: str = "/Game/ASA/Dinos/DarkPegasus/DarkPegasus_AIController_BP.DarkPegasus_AIController_BP_C"
    deinosuchus_asa: str = "/Game/ASA/Dinos/Deinosuchus/Deinosuchus_AIController_BP_ASA.Deinosuchus_AIController_BP_ASA_C"
    deinotherium_asa: str = "/Game/ASA/Dinos/Deinotherium/Dinos/Deinotherium_AI_Blueprint_ASA.Deinotherium_AI_Blueprint_ASA_C"
    fasola: str = "/Game/ASA/Dinos/Fasolasuchus/Fasola_AIController_BP.Fasola_AIController_BP_C"
    fire_lion: str = "/Game/ASA/Dinos/FireLion/FireLion_AIController_BP.FireLion_AIController_BP_C"
    gigantoraptor: str = "/Game/ASA/Dinos/Gigantoraptor/Gigantoraptor_AIController_BP.Gigantoraptor_AIController_BP_C"
    helicoprion: str = "/Game/ASA/Dinos/Helicoprion/Helicoprion_AIController_BP.Helicoprion_AIController_BP_C"
    rag_ice_wyvern: str = "/Game/ASA/Dinos/IceWyvern/RAG_IceWyvern_AI.RAG_IceWyvern_AI_C"
    shoulder_dragon: str = "/Game/ASA/Dinos/ShoulderDragon/ShoulderDragon_AIController_BP.ShoulderDragon_AIController_BP_C"
    xiphactinus_asa: str = "/Game/ASA/Dinos/Xiphactinus/Dinos/Xiphactinus_AIController_BP_ASA.Xiphactinus_AIController_BP_ASA_C"
    yi_ling: str = "/Game/ASA/Dinos/YiLing/YiLing_AIController_BP.YiLing_AIController_BP_C"
    cave_wolf: str = "/Game/Aberration/Dinos/CaveWolf/CaveWolf_AIController_BP.CaveWolf_AIController_BP_C"
    chupa_cabra: str = "/Game/Aberration/Dinos/ChupaCabra/ChupaCabra_AIController_BP.ChupaCabra_AIController_BP_C"
    crab: str = "/Game/Aberration/Dinos/Crab/Crab_AIController_BP.Crab_AIController_BP_C"
    lantern_pug: str = "/Game/Aberration/Dinos/LanternPug/LanternPug_AIController_BP.LanternPug_AIController_BP_C"
    light_bug: str = "/Game/Aberration/Dinos/Lightbug/LightBug_AIController_BP.LightBug_AIController_BP_C"
    mole_rat: str = "/Game/Aberration/Dinos/MoleRat/MoleRat_AIController_BP.MoleRat_AIController_BP_C"
    xenomorph_female: str = "/Game/Aberration/Dinos/Nameless/Xenomorph_Female_AIController_BP.Xenomorph_Female_AIController_BP_C"
    rock_drake: str = "/Game/Aberration/Dinos/RockDrake/RockDrake_AIController_BP.RockDrake_AIController_BP_C"
    dilo_corrupt: str = "/Game/Extinction/Dinos/Corrupt/Dilo/Dilo_AIController_BP_Corrupt.Dilo_AIController_BP_Corrupt_C"
    ptero_corrupt: str = "/Game/Extinction/Dinos/Corrupt/Ptero/Ptero_AIController_BP_Corrupt.Ptero_AIController_BP_Corrupt_C"
    raptor_corrupt: str = "/Game/Extinction/Dinos/Corrupt/Raptor/Raptor_AIController_BP_Corrupt.Raptor_AIController_BP_Corrupt_C"
    rex_corrupt: str = "/Game/Extinction/Dinos/Corrupt/Rex/Rex_AIController_BP_Corrupt.Rex_AIController_BP_Corrupt_C"
    rock_drake_corrupt: str = "/Game/Extinction/Dinos/Corrupt/RockDrake/RockDrake_AIController_BP_Corrupt.RockDrake_AIController_BP_Corrupt_C"
    spino_corrupt: str = "/Game/Extinction/Dinos/Corrupt/Spino/Spino_AI_Blueprint_Corrupt.Spino_AI_Blueprint_Corrupt_C"
    trike_corrupt: str = "/Game/Extinction/Dinos/Corrupt/Trike/Trike_AIController_BP_Corrupt.Trike_AIController_BP_Corrupt_C"
    gacha: str = "/Game/Extinction/Dinos/Gacha/AI/Gacha_AIController_BP.Gacha_AIController_BP_C"
    ice_jumper: str = "/Game/Extinction/Dinos/IceJumper/IceJumper_AIController_BP.IceJumper_AIController_BP_C"
    owl: str = "/Game/Extinction/Dinos/Owl/AI/Owl_AIController_BP.Owl_AIController_BP_C"
    spindles: str = "/Game/Extinction/Dinos/Spindles/Spindles_AIController_BP.Spindles_AIController_BP_C"
    desmodus: str = "/Game/Fjordur/Dinos/Desmodus/Desmodus_AIController_BP.Desmodus_AIController_BP_C"
    cherufe: str = "/Game/Genesis/Dinos/Cherufe/Cherufe_AIController_BP.Cherufe_AIController_BP_C"
    milk_glider: str = "/Game/Genesis2/Dinos/MilkGlider/MilkGlider_AIController_BP.MilkGlider_AIController_BP_C"
    lost_charge_pet: str = "/Game/LostColony/Dinos/LostChargePet/AI/LostChargePet_AIController_BP.LostChargePet_AIController_BP_C"
    snow_monster: str = "/Game/LostColony/Dinos/SnowMonster/SnowMonster_AIController_BP.SnowMonster_AIController_BP_C"
    thrall_tamed: str = "/Game/LostColony/Dinos/Thrall/Characters/Base/Thrall_AIController_BP_Tamed.Thrall_AIController_BP_Tamed_C"
    young_ice_fox: str = "/Game/LostColony/Dinos/YoungIceFox/YoungIceFox_AIController_BP.YoungIceFox_AIController_BP_C"
    oasisaur: str = "/Game/Packs/Frontier/Dinos/Oasisaur/Oasisaur_AIController_BP.Oasisaur_AIController_BP_C"
    helper_bot: str = "/Game/Packs/Steampunk/Dinos/HelperBot/HelperBot_AIController_BP.HelperBot_AIController_BP_C"
    jumping_spider: str = "/Game/Packs/Steampunk/Dinos/JumpingSpider/JumpingSpider_AIController_BP.JumpingSpider_AIController_BP_C"
    axolotl_small: str = "/Game/Packs/TidesOfFortune/Dinos/Axolotl/Axolotl_Small/Axolotl_Small_AIController_BP.Axolotl_Small_AIController_BP_C"
    parrot: str = "/Game/Packs/TidesOfFortune/Dinos/Parrot/Parrot_AIController_BP.Parrot_AIController_BP_C"
    doggo: str = "/Game/Packs/Wasteland/Dinos/Doggo/Doggo_AIController_BP.Doggo_AIController_BP_C"
    achatina: str = "/Game/PrimalEarth/Dinos/Achatina/Achatina_AIController.Achatina_AIController_C"
    allo: str = "/Game/PrimalEarth/Dinos/Allosaurus/Allo_AIController_BP.Allo_AIController_BP_C"
    ammonite: str = "/Game/PrimalEarth/Dinos/Ammonite/Ammonite_AIController.Ammonite_AIController_C"
    angler: str = "/Game/PrimalEarth/Dinos/Anglerfish/Angler_AIController_BP.Angler_AIController_BP_C"
    ankylo: str = "/Game/PrimalEarth/Dinos/Ankylo/Ankylo_AIController_BP.Ankylo_AIController_BP_C"
    ant: str = "/Game/PrimalEarth/Dinos/Ant/Ant_AIController.Ant_AIController_C"
    flying_ant: str = "/Game/PrimalEarth/Dinos/Ant/FlyingAnt_AIController_BP.FlyingAnt_AIController_BP_C"
    archa: str = "/Game/PrimalEarth/Dinos/Archaeopteryx/Archa_AIController_BP.Archa_AIController_BP_C"
    argent: str = "/Game/PrimalEarth/Dinos/Argentavis/Argent_AIController_BP.Argent_AIController_BP_C"
    arthro: str = "/Game/PrimalEarth/Dinos/Arthropluera/Arthro_AIController_BP.Arthro_AIController_BP_C"
    baryonyx: str = "/Game/PrimalEarth/Dinos/Baryonyx/Baryonyx_AIController_BP.Baryonyx_AIController_BP_C"
    basilosaurus: str = "/Game/PrimalEarth/Dinos/Basilosaurus/Basilosaurus_AIController_BP.Basilosaurus_AIController_BP_C"
    bat: str = "/Game/PrimalEarth/Dinos/Bat/Bat_AIController_BP.Bat_AIController_BP_C"
    beaver: str = "/Game/PrimalEarth/Dinos/Beaver/Beaver_AIController_BP.Beaver_AIController_BP_C"
    bigfoot: str = "/Game/PrimalEarth/Dinos/Bigfoot/Bigfoot_AIController_BP.Bigfoot_AIController_BP_C"
    boa_frill: str = "/Game/PrimalEarth/Dinos/BoaFrill/BoaFrill_AIController_BP.BoaFrill_AIController_BP_C"
    carcha: str = "/Game/PrimalEarth/Dinos/Carcharodontosaurus/Carcha_AIController_BP.Carcha_AIController_BP_C"
    carno: str = "/Game/PrimalEarth/Dinos/Carno/Carno_AIController_BP.Carno_AIController_BP_C"
    chalico: str = "/Game/PrimalEarth/Dinos/Chalicotherium/Chalico_AIController_BP.Chalico_AIController_BP_C"
    cnidaria: str = "/Game/PrimalEarth/Dinos/Cnidaria/Cnidaria_AIController_BP.Cnidaria_AIController_BP_C"
    coel: str = "/Game/PrimalEarth/Dinos/Coelacanth/Coel_AIController_BP.Coel_AIController_BP_C"
    compy: str = "/Game/PrimalEarth/Dinos/Compy/Compy_AIController.Compy_AIController_C"
    daeodon: str = "/Game/PrimalEarth/Dinos/Daeodon/Daeodon_AIController_BP.Daeodon_AIController_BP_C"
    dilo: str = "/Game/PrimalEarth/Dinos/Dilo/Dilo_AIController_BP.Dilo_AIController_BP_C"
    dimetrodon: str = "/Game/PrimalEarth/Dinos/Dimetrodon/Dimetrodon_AIController_BP.Dimetrodon_AIController_BP_C"
    dimorph: str = "/Game/PrimalEarth/Dinos/Dimorphodon/Dimorph_AIController_BP.Dimorph_AIController_BP_C"
    diplocaulus: str = "/Game/PrimalEarth/Dinos/Diplocaulus/Diplocaulus_AIController_BP.Diplocaulus_AIController_BP_C"
    diplo: str = "/Game/PrimalEarth/Dinos/Diplodocus/Diplo_AI_Blueprint.Diplo_AI_Blueprint_C"
    bear: str = "/Game/PrimalEarth/Dinos/Direbear/Bear_AIController_BP.Bear_AIController_BP_C"
    direwolf: str = "/Game/PrimalEarth/Dinos/Direwolf/Direwolf_AIController_BP.Direwolf_AIController_BP_C"
    dodo: str = "/Game/PrimalEarth/Dinos/Dodo/Dodo_AIController_BP.Dodo_AIController_BP_C"
    doed: str = "/Game/PrimalEarth/Dinos/Doedicurus/Doed_AIController_BP.Doed_AIController_BP_C"
    dolphin: str = "/Game/PrimalEarth/Dinos/Dolphin/Dolphin_AIController_BP.Dolphin_AIController_BP_C"
    dung_beetle: str = "/Game/PrimalEarth/Dinos/DungBeetle/DungBeetle_AIController.DungBeetle_AIController_C"
    dunkle: str = "/Game/PrimalEarth/Dinos/Dunkleosteus/Dunkle_AIController_BP.Dunkle_AIController_BP_C"
    eel: str = "/Game/PrimalEarth/Dinos/Eel/Eel_AIController_BP.Eel_AIController_BP_C"
    equus: str = "/Game/PrimalEarth/Dinos/Equus/Equus_AI_Blueprint.Equus_AI_Blueprint_C"
    euryp: str = "/Game/PrimalEarth/Dinos/Eurypterid/Euryp_AIController.Euryp_AIController_C"
    gallimimus: str = "/Game/PrimalEarth/Dinos/Gallimimus/Gallimimus_AI_Blueprint.Gallimimus_AI_Blueprint_C"
    gigant: str = "/Game/PrimalEarth/Dinos/Giganotosaurus/Gigant_AIController_BP.Gigant_AIController_BP_C"
    griffin: str = "/Game/PrimalEarth/Dinos/Griffin/Griffin_AIController_BP.Griffin_AIController_BP_C"
    hesperornis: str = "/Game/PrimalEarth/Dinos/Hesperornis/Hesperornis_AIController_BP.Hesperornis_AIController_BP_C"
    hyaenodon: str = "/Game/PrimalEarth/Dinos/Hyaenodon/Hyaenodon_AIController_BP.Hyaenodon_AIController_BP_C"
    ichthyornis: str = "/Game/PrimalEarth/Dinos/Ichthyornis/Ichthyornis_AIController_BP.Ichthyornis_AIController_BP_C"
    iguanodon: str = "/Game/PrimalEarth/Dinos/Iguanodon/Iguanodon_AI_Controller.Iguanodon_AI_Controller_C"
    kairuku: str = "/Game/PrimalEarth/Dinos/Kairuku/Kairuku_AIController_BP.Kairuku_AIController_BP_C"
    kaprosuchus: str = "/Game/PrimalEarth/Dinos/Kaprosuchus/Kaprosuchus_AIController_BP.Kaprosuchus_AIController_BP_C"
    kentro: str = "/Game/PrimalEarth/Dinos/Kentrosaurus/Kentro_AIController_BP.Kentro_AIController_BP_C"
    lystro: str = "/Game/PrimalEarth/Dinos/Lystrosaurus/Lystro_AIController_BP.Lystro_AIController_BP_C"
    mammoth: str = "/Game/PrimalEarth/Dinos/Mammoth/Mammoth_AI_Blueprint.Mammoth_AI_Blueprint_C"
    manta: str = "/Game/PrimalEarth/Dinos/Manta/Manta_AIController_BP.Manta_AIController_BP_C"
    megalania: str = "/Game/PrimalEarth/Dinos/Megalania/Megalania_AIController_BP.Megalania_AIController_BP_C"
    megalodon: str = "/Game/PrimalEarth/Dinos/Megalodon/Megalodon_AIController_BP.Megalodon_AIController_BP_C"
    megalosaurus: str = "/Game/PrimalEarth/Dinos/Megalosaurus/Megalosaurus_AIController_BP.Megalosaurus_AIController_BP_C"
    megatherium: str = "/Game/PrimalEarth/Dinos/Megatherium/Megatherium_AIController_BP.Megatherium_AIController_BP_C"
    microraptor: str = "/Game/PrimalEarth/Dinos/Microraptor/Microraptor_AIController_BP.Microraptor_AIController_BP_C"
    monkey: str = "/Game/PrimalEarth/Dinos/Monkey/Monkey_AIController_BP.Monkey_AIController_BP_C"
    moschops: str = "/Game/PrimalEarth/Dinos/Moschops/Moschops_AIController_BP.Moschops_AIController_BP_C"
    otter: str = "/Game/PrimalEarth/Dinos/Otter/Otter_AIController_BP.Otter_AIController_BP_C"
    oviraptor: str = "/Game/PrimalEarth/Dinos/Oviraptor/Oviraptor_AIController_BP.Oviraptor_AIController_BP_C"
    pachy: str = "/Game/PrimalEarth/Dinos/Pachy/Pachy_AIController_BP.Pachy_AIController_BP_C"
    pachyrhino: str = "/Game/PrimalEarth/Dinos/Pachyrhinosaurus/Pachyrhino_AIController_BP.Pachyrhino_AIController_BP_C"
    para: str = "/Game/PrimalEarth/Dinos/Para/Para_AI_Blueprint.Para_AI_Blueprint_C"
    paracer: str = "/Game/PrimalEarth/Dinos/Paraceratherium/Paracer_AI_Blueprint.Paracer_AI_Blueprint_C"
    pegomastax: str = "/Game/PrimalEarth/Dinos/Pegomastax/Pegomastax_AIController_BP.Pegomastax_AIController_BP_C"
    pela: str = "/Game/PrimalEarth/Dinos/Pelagornis/Pela_AIController_BP.Pela_AIController_BP_C"
    phiomia: str = "/Game/PrimalEarth/Dinos/Phiomia/Phiomia_AIController_BP.Phiomia_AIController_BP_C"
    piranha: str = "/Game/PrimalEarth/Dinos/Piranha/Piranha_AIController_BP.Piranha_AIController_BP_C"
    proc: str = "/Game/PrimalEarth/Dinos/Procoptodon/Proc_AIController_BP.Proc_AIController_BP_C"
    ptero: str = "/Game/PrimalEarth/Dinos/Ptero/Ptero_AIController_BP.Ptero_AIController_BP_C"
    purlovia: str = "/Game/PrimalEarth/Dinos/Purlovia/Purlovia_AIController_BP.Purlovia_AIController_BP_C"
    quetz: str = "/Game/PrimalEarth/Dinos/Quetzalcoatlus/Quetz_AIController_BP.Quetz_AIController_BP_C"
    mega_raptor: str = "/Game/PrimalEarth/Dinos/Raptor/MegaRaptor_AIController_BP.MegaRaptor_AIController_BP_C"
    raptor: str = "/Game/PrimalEarth/Dinos/Raptor/Raptor_AIController_BP.Raptor_AIController_BP_C"
    rex: str = "/Game/PrimalEarth/Dinos/Rex/Rex_AIController_BP.Rex_AIController_BP_C"
    rhynio: str = "/Game/PrimalEarth/Dinos/Rhyniognatha/Rhynio_AIController_BP.Rhynio_AIController_BP_C"
    saber: str = "/Game/PrimalEarth/Dinos/Saber/Saber_AIController_BP.Saber_AIController_BP_C"
    salmon: str = "/Game/PrimalEarth/Dinos/Salmon/Salmon_AIController_BP.Salmon_AIController_BP_C"
    sarco: str = "/Game/PrimalEarth/Dinos/Sarco/Sarco_AIController_BP.Sarco_AIController_BP_C"
    sauropod: str = "/Game/PrimalEarth/Dinos/Sauropod/Sauropod_AI_Blueprint.Sauropod_AI_Blueprint_C"
    scorpion: str = "/Game/PrimalEarth/Dinos/Scorpion/Scorpion_AIController_BP.Scorpion_AIController_BP_C"
    sheep: str = "/Game/PrimalEarth/Dinos/Sheep/Sheep_AIController_BP.Sheep_AIController_BP_C"
    spider: str = "/Game/PrimalEarth/Dinos/Spider-Small/Spider_AIController.Spider_AIController_C"
    spino: str = "/Game/PrimalEarth/Dinos/Spino/Spino_AI_Blueprint.Spino_AI_Blueprint_C"
    stag: str = "/Game/PrimalEarth/Dinos/Stag/Stag_AIController_BP.Stag_AIController_BP_C"
    stego: str = "/Game/PrimalEarth/Dinos/Stego/Stego_AIController_BP.Stego_AIController_BP_C"
    tapejara: str = "/Game/PrimalEarth/Dinos/Tapejara/Tapejara_AIController_BP.Tapejara_AIController_BP_C"
    terror_bird: str = "/Game/PrimalEarth/Dinos/TerrorBird/TerrorBird_AIController_BP.TerrorBird_AIController_BP_C"
    therizino: str = "/Game/PrimalEarth/Dinos/Therizinosaurus/Therizino_AIController_BP.Therizino_AIController_BP_C"
    thylacoleo: str = "/Game/PrimalEarth/Dinos/Thylacoleo/Thylacoleo_AIController_BP.Thylacoleo_AIController_BP_C"
    toad: str = "/Game/PrimalEarth/Dinos/Toad/Toad_AIController_BP.Toad_AIController_BP_C"
    trike: str = "/Game/PrimalEarth/Dinos/Trike/Trike_AIController_BP.Trike_AIController_BP_C"
    trilobite: str = "/Game/PrimalEarth/Dinos/Trilobite/Trilobite_AIController.Trilobite_AIController_C"
    troodon: str = "/Game/PrimalEarth/Dinos/Troodon/Troodon_AIController_BP.Troodon_AIController_BP_C"
    turtle: str = "/Game/PrimalEarth/Dinos/Turtle/Turtle_AIController_BP.Turtle_AIController_BP_C"
    tusoteuthis: str = "/Game/PrimalEarth/Dinos/Tusoteuthis/Tusoteuthis_AIController_BP.Tusoteuthis_AIController_BP_C"
    rhino: str = "/Game/PrimalEarth/Dinos/WoollyRhino/Rhino_AIController_BP.Rhino_AIController_BP_C"
    yutyrannus: str = "/Game/PrimalEarth/Dinos/Yutyrannus/Yutyrannus_AIController_BP.Yutyrannus_AIController_BP_C"
    camelsaurus: str = "/Game/ScorchedEarth/Dinos/Camelsaurus/camelsaurus_AIController_BP.camelsaurus_AIController_BP_C"
    jerboa: str = "/Game/ScorchedEarth/Dinos/Jerboa/Jerboa_AIController_BP.Jerboa_AIController_BP_C"
    jugbug: str = "/Game/ScorchedEarth/Dinos/JugBug/Jugbug_AIController_BP.Jugbug_AIController_BP_C"
    mantis: str = "/Game/ScorchedEarth/Dinos/Mantis/Mantis_AIController.Mantis_AIController_C"
    moth: str = "/Game/ScorchedEarth/Dinos/Moth/Moth_AIController_BP.Moth_AIController_BP_C"
    phoenix: str = "/Game/ScorchedEarth/Dinos/Phoenix/Phoenix_AIController_BP.Phoenix_AIController_BP_C"
    rock_golem: str = "/Game/ScorchedEarth/Dinos/RockGolem/RockGolem_AIController_BP.RockGolem_AIController_BP_C"
    spiney_lizard: str = "/Game/ScorchedEarth/Dinos/SpineyLizard/SpineyLizard_AIController_BP.SpineyLizard_AIController_BP_C"
    vulture: str = "/Game/ScorchedEarth/Dinos/Vulture/Vulture_AIController_BP.Vulture_AIController_BP_C"
    wyvern: str = "/Game/ScorchedEarth/Dinos/Wyvern/Wyvern_AIController_BP.Wyvern_AIController_BP_C"
    wyvern_lightning: str = "/Game/ScorchedEarth/Dinos/Wyvern/Wyvern_AIController_BP_Lightning.Wyvern_AIController_BP_Lightning_C"

    all_bps = [acro, archelon_asa, bison, cat, cat_tamed, cerato_asa, cryolophosaurus, dark_pegasus,
               deinosuchus_asa, deinotherium_asa, fasola, fire_lion, gigantoraptor, helicoprion,
               rag_ice_wyvern, shoulder_dragon, xiphactinus_asa, yi_ling, cave_wolf, chupa_cabra, crab,
               lantern_pug, light_bug, mole_rat, xenomorph_female, rock_drake, dilo_corrupt, ptero_corrupt,
               raptor_corrupt, rex_corrupt, rock_drake_corrupt, spino_corrupt, trike_corrupt, gacha,
               ice_jumper, owl, spindles, desmodus, cherufe, milk_glider, lost_charge_pet, snow_monster,
               thrall_tamed, young_ice_fox, oasisaur, helper_bot, jumping_spider, axolotl_small, parrot,
               doggo, achatina, allo, ammonite, angler, ankylo, ant, flying_ant, archa, argent, arthro,
               baryonyx, basilosaurus, bat, beaver, bigfoot, boa_frill, carcha, carno, chalico, cnidaria,
               coel, compy, daeodon, dilo, dimetrodon, dimorph, diplocaulus, diplo, bear, direwolf, dodo,
               doed, dolphin, dung_beetle, dunkle, eel, equus, euryp, gallimimus, gigant, griffin,
               hesperornis, hyaenodon, ichthyornis, iguanodon, kairuku, kaprosuchus, kentro, lystro, mammoth,
               manta, megalania, megalodon, megalosaurus, megatherium, microraptor, monkey, moschops, otter,
               oviraptor, pachy, pachyrhino, para, paracer, pegomastax, pela, phiomia, piranha, proc, ptero,
               purlovia, quetz, mega_raptor, raptor, rex, rhynio, saber, salmon, sarco, sauropod, scorpion,
               sheep, spider, spino, stag, stego, tapejara, terror_bird, therizino, thylacoleo, toad, trike,
               trilobite, troodon, turtle, tusoteuthis, rhino, yutyrannus, camelsaurus, jerboa, jugbug,
               mantis, moth, phoenix, rock_golem, spiney_lizard, vulture, wyvern, wyvern_lightning]

class HarvestComponents:
    gargoyle_harvest_component: str = "/Game/LostColony/Dinos/Gargoyle/GargoyleHarvestComponent.GargoyleHarvestComponent_C"
    huge: str = "/Game/PrimalEarth/CoreBlueprints/HarvestComponents/DinoDeathHarvestingComponent_Huge.DinoDeathHarvestingComponent_Huge_C"
    huge_more_meat: str = "/Game/PrimalEarth/CoreBlueprints/HarvestComponents/DinoDeathHarvestingComponent_Huge_MoreMeat.DinoDeathHarvestingComponent_Huge_MoreMeat_C"
    lamb: str = "/Game/PrimalEarth/CoreBlueprints/HarvestComponents/DinoDeathHarvestingComponent_Lamb.DinoDeathHarvestingComponent_Lamb_C"
    large: str = "/Game/PrimalEarth/CoreBlueprints/HarvestComponents/DinoDeathHarvestingComponent_Large.DinoDeathHarvestingComponent_Large_C"
    large_less_keratin: str = "/Game/PrimalEarth/CoreBlueprints/HarvestComponents/DinoDeathHarvestingComponent_Large_LessKeratin.DinoDeathHarvestingComponent_Large_LessKeratin_C"
    medium: str = "/Game/PrimalEarth/CoreBlueprints/HarvestComponents/DinoDeathHarvestingComponent_Medium.DinoDeathHarvestingComponent_Medium_C"
    medium_keratin_and_hide: str = "/Game/PrimalEarth/CoreBlueprints/HarvestComponents/DinoDeathHarvestingComponent_Medium_KeratinAndHide.DinoDeathHarvestingComponent_Medium_KeratinAndHide_C"
    medium_more_hide: str = "/Game/PrimalEarth/CoreBlueprints/HarvestComponents/DinoDeathHarvestingComponent_Medium_MoreHide.DinoDeathHarvestingComponent_Medium_MoreHide_C"
    small: str = "/Game/PrimalEarth/CoreBlueprints/HarvestComponents/DinoDeathHarvestingComponent_Small.DinoDeathHarvestingComponent_Small_C"
    small_less_keratin: str = "/Game/PrimalEarth/CoreBlueprints/HarvestComponents/DinoDeathHarvestingComponent_Small_LessKeratin.DinoDeathHarvestingComponent_Small_LessKeratin_C"
    small_pelt: str = "/Game/PrimalEarth/CoreBlueprints/HarvestComponents/DinoDeathHarvestingComponent_Small_Pelt.DinoDeathHarvestingComponent_Small_Pelt_C"
    tiny: str = "/Game/PrimalEarth/CoreBlueprints/HarvestComponents/DinoDeathHarvestingComponent_Tiny.DinoDeathHarvestingComponent_Tiny_C"
    tiny_meat_only: str = "/Game/PrimalEarth/CoreBlueprints/HarvestComponents/DinoDeathHarvestingComponent_Tiny_MeatOnly.DinoDeathHarvestingComponent_Tiny_MeatOnly_C"
    tiny_organo_polymer: str = "/Game/PrimalEarth/CoreBlueprints/HarvestComponents/DinoDeathHarvestingComponent_Tiny_OrganoPolymer.DinoDeathHarvestingComponent_Tiny_OrganoPolymer_C"
    tiny_pelt: str = "/Game/PrimalEarth/CoreBlueprints/HarvestComponents/DinoDeathHarvestingComponent_Tiny_Pelt.DinoDeathHarvestingComponent_Tiny_Pelt_C"
    huge_wyvern: str = "/Game/ScorchedEarth/CoreBlueprints/HarvestComponents/DinoDeathHarvestingComponent_Huge_Wyvern.DinoDeathHarvestingComponent_Huge_Wyvern_C"
    tiny_lots_hide: str = "/Game/ScorchedEarth/CoreBlueprints/HarvestComponents/DinoDeathHarvestingComponent_Tiny_LotsHide.DinoDeathHarvestingComponent_Tiny_LotsHide_C"

    all_bps = [gargoyle_harvest_component, huge, huge_more_meat, lamb, large, large_less_keratin, medium,
               medium_keratin_and_hide, medium_more_hide, small, small_less_keratin, small_pelt, tiny,
               tiny_meat_only, tiny_organo_polymer, tiny_pelt, huge_wyvern, tiny_lots_hide]

class DinoComponents:
    status_components: StatusComponents = StatusComponents()
    inventory_components: InventoryComponents = InventoryComponents()
    ai_controllers: AIControllers = AIControllers()
    harvest_components: HarvestComponents = HarvestComponents()

    all_bps = status_components.all_bps + inventory_components.all_bps + ai_controllers.all_bps + \
        harvest_components.all_bps
